on:
  schedule:
    - cron: '53 9 */3 * *'
  push:
    branches:
      - master


jobs:
  win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt
      - run: pip install pyinstaller
      - run: pyinstaller odpy.spec
      - run: move config/, data/, data-global/, mods/, *.js, game.txt, mumu.txt, README.md, syncData.json dist/odpy/
      - run: python update_cache.py
      - run: move adb.zip, frida-server-*.xz, aria2c.exe, bat-for-exe/run.cmd dist/odpy/ -ErrorAction SilentlyContinue
      - uses: actions/upload-artifact@v4
        with:
          name: windows
          path: dist/odpy/
